### ISSUE TITLE
可以尝试改为设置Integer.MAX_VAlUE的方式呢？

### ISSUE THREAD

**Issue by ghost** [wangpeiyuan/CycleViewPager2#4]
可以节省不少代码٩(๑❛ᴗ❛๑)۶

**Comment by wangpeiyuan** [comment]
应该可以，后续找个时间尝试一下

**Comment by NaJiPeng** [comment]
使用Integer.MAX_VAlUE的方式实现了无限循环轮播的效果，而且不需要对ViewPager2进行任何额外操作，只需要设置Adapter就能获得无限轮播的功能。下面是我的代码，希望对你有所帮助：
[https://github.com/NaJiPeng/ViewPager2BannerHelper/tree/master/library/src/main/java/com/njp/library/loop](url)
